apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dapr
  namespace: argocd
spec:
  project: default
  source:
    chart: dapr
    repoURL: https://dapr.github.io/helm-charts/
    targetRevision: 1.15.4
    helm:
      parameters:
      - name: "dapr_operator.livenessProbe.initialDelaySeconds"
        value: 10
  destination:
    server: "https://kubernetes.default.svc"
    namespace: appns